// Regenerates website/assets/js/body-atlas.js (male front + back figure for
// the muscle-map demo) from the app's own data, with the same slug->muscle
// mapping and the same front/side-delt and upper-back/lats splits as
// mobile/lib/data/body_atlas.dart.
//
// Run from the repo root:
//   npm install --no-save svg-path-bbox
//   node website/tools/extract-body.mjs
import fs from 'node:fs';
import { svgPathBbox } from 'svg-path-bbox';

const src = fs.readFileSync('mobile/lib/data/body_atlas_data.dart', 'utf8');

function parts(name) {
  const start = src.indexOf(`const List<AtlasPart> ${name} = [`);
  if (start < 0) throw new Error(`missing ${name}`);
  const text = src.slice(start, src.indexOf('\n];', start));
  const out = [];
  const re = /AtlasPart\("([^"]+)",\s*"([^"]+)",\s*\[([\s\S]*?)\]\)/g;
  let m;
  while ((m = re.exec(text))) {
    out.push({ slug: m[1], side: m[2], paths: [...m[3].matchAll(/"([^"]+)"/g)].map((x) => x[1]) });
  }
  return out;
}

function bbox(paths) {
  let [x0, y0, x1, y1] = [Infinity, Infinity, -Infinity, -Infinity];
  for (const d of paths) {
    const [a, b, c, e] = svgPathBbox(d);
    x0 = Math.min(x0, a); y0 = Math.min(y0, b); x1 = Math.max(x1, c); y1 = Math.max(y1, e);
  }
  return { x0, y0, x1, y1, w: x1 - x0, h: y1 - y0, cx: (x0 + x1) / 2 };
}

const r1 = (v) => Math.round(v * 10) / 10;
const WIDTH = 724; // kAtlasWidth: the back view sits at x 724-1448
const HEIGHT = 1448;

// _directMuscleForSlug in body_atlas.dart
const FRONT = { chest: 'chest', obliques: 'obliques', abs: 'abs', biceps: 'biceps', quadriceps: 'quads', calves: 'calves', forearm: 'forearms' };
const BACK = { trapezius: 'traps', triceps: 'triceps', 'lower-back': 'lowerBack', gluteal: 'glutes', hamstring: 'hamstrings' };

function view(name, front) {
  const xOffset = front ? 0 : WIDTH;
  const centerline = xOffset + WIDTH / 2;
  const shapes = [];
  for (const part of parts(name)) {
    const d = part.paths.join('');
    if (part.slug === 'deltoids') {
      if (!front) {
        shapes.push({ d, m: 'rearDelts' });
        continue;
      }
      // _splitDeltoid: medial 56/44 split, detected per side
      const b = bbox(part.paths);
      const left = b.cx < centerline;
      const splitX = b.x0 + b.w * (left ? 0.56 : 0.44);
      const top = b.y0 - 12;
      const height = b.h + 24;
      const outer = left ? [b.x0 - 12, top, splitX - (b.x0 - 12), height] : [splitX, top, b.x1 + 12 - splitX, height];
      const inner = left ? [splitX, top, b.x1 + 12 - splitX, height] : [b.x0 - 12, top, splitX - (b.x0 - 12), height];
      shapes.push({ d, m: 'frontDelts', clip: inner.map(r1) });
      shapes.push({ d, m: 'sideDelts', clip: outer.map(r1) });
      continue;
    }
    if (part.slug === 'upper-back') {
      // _splitUpperBack: top 30% upper back, the rest lats
      const b = bbox(part.paths);
      const splitY = b.y0 + b.h * 0.3;
      shapes.push({ d, m: 'upperBack', clip: [b.x0 - 12, b.y0 - 12, b.w + 24, splitY - (b.y0 - 12)].map(r1) });
      shapes.push({ d, m: 'lats', clip: [b.x0 - 12, splitY, b.w + 24, b.y1 + 12 - splitY].map(r1) });
      continue;
    }
    const m = (front ? FRONT : BACK)[part.slug];
    shapes.push(m ? { d, m } : { d });
  }
  return { viewBox: `${xOffset} 0 ${WIDTH} ${HEIGHT}`, shapes };
}

const data = { front: view('maleFrontRaw', true), back: view('maleBackRaw', false) };
const header = `/*!
 * Ironpeak body figure for the muscle-map demo (male front + back view).
 *
 * Path data: "react-native-body-highlighter" by Hicham ELABBASSI
 * https://github.com/HichamELBSI/react-native-body-highlighter
 * MIT License, Copyright (c) 2022 ELABBASSI Hicham. Permission is hereby
 * granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files, to deal in the software without
 * restriction, subject to including this copyright notice.
 *
 * Generated by website/tools/extract-body.mjs from
 * mobile/lib/data/body_atlas_data.dart with the app's own
 * muscle mapping and front/side-delt + upper-back/lats splits
 * (mobile/lib/data/body_atlas.dart). "clip" is the split's rectangle
 * [x, y, w, h] in the figure's coordinates. Do not hand-edit.
 */
`;
fs.writeFileSync('website/assets/js/body-atlas.js', `${header}window.IronpeakBody = ${JSON.stringify(data)};\n`);
console.log('wrote website/assets/js/body-atlas.js');
