import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ironpeak_mobile/data/exercise_gifs.dart';

/// Guards data/exercise_gifs.dart (regenerated by tooling) against drifting
/// out of sync with assets/exercises.json, and against values that aren't
/// dataset basenames -- those would become broken URLs/cache file names.
/// Two ids may deliberately share one animation, so values need not be
/// unique.
void main() {
  test('every kExerciseGifs key is an id in assets/exercises.json', () {
    final file = File('assets/exercises.json');
    expect(file.existsSync(), isTrue, reason: 'run from the mobile/ directory');
    final decoded = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final ids = {
      for (final e in decoded['exercises'] as List) (e as Map<String, dynamic>)['id'] as String,
    };
    expect(kExerciseGifs, isNotEmpty);
    for (final id in kExerciseGifs.keys) {
      expect(ids.contains(id), isTrue, reason: '"$id" is not an exercise id');
    }
  });

  test('every kExerciseGifs value is a dataset media basename', () {
    final pattern = RegExp(r'^\d{4}-[A-Za-z0-9]{7}$');
    kExerciseGifs.forEach((id, basename) {
      expect(pattern.hasMatch(basename), isTrue, reason: '"$id" -> "$basename"');
    });
  });
}
