// Regenerates every static icon asset from the logo painter in
// lib/widgets/ironpeak_logo.dart, so they all come from one source:
//
//   * Android: adaptive icon (background / foreground / themed monochrome),
//     the animated launch icon, and the legacy mipmap PNGs
//   * web: favicon + PWA icons
//   * Windows: runner/resources/app_icon.ico
//   * tool/branding/ironpeak_icon_1024.png -- full-bleed master for iOS/macOS
//
// Run from mobile/ (it needs the Flutter engine for dart:ui, hence
// `flutter test`, not `dart run`; it lives in tool/ so a plain
// `flutter test` never rewrites resources):
//
//   flutter test tool/generate_icons.dart
//
// Optional env vars:
//   IRONPEAK_PREVIEW_DIR=<dir>   also write a contact sheet of the animation
//   IRONPEAK_SKIP_ASSETS=1       preview only, leave the project untouched
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ironpeak_mobile/widgets/ironpeak_logo.dart';

const String _res = 'android/app/src/main/res';

void main() {
  testWidgets('generate icon assets', (tester) async {
    await tester.runAsync(() async {
      final preview = Platform.environment['IRONPEAK_PREVIEW_DIR'];
      if (preview != null && preview.isNotEmpty) {
        await _writePreview(Directory(preview));
      }
      if (Platform.environment['IRONPEAK_SKIP_ASSETS'] == '1') return;

      await _writeAndroid();
      await _writeWeb();
      await _writeWindows();
      await _write(
        'tool/branding/ironpeak_icon_1024.png',
        await _png(1024, shape: LogoShape.square),
      );
    });
  });
}

// --- rendering ---------------------------------------------------------

Future<ui.Image> _render(
  int px, {
  LogoShape shape = LogoShape.roundedSquare,
  LogoPose pose = LogoPose.rest,
  double glyph = IronpeakMark.badgeGlyphFraction,
}) {
  final recorder = ui.PictureRecorder();
  final canvas = Canvas(recorder);
  IronpeakMark.paint(
    canvas,
    Size.square(px.toDouble()),
    shape: shape,
    pose: pose,
    glyphFraction: glyph,
  );
  return recorder.endRecording().toImage(px, px);
}

Future<Uint8List> _png(
  int px, {
  LogoShape shape = LogoShape.roundedSquare,
  double glyph = IronpeakMark.badgeGlyphFraction,
}) async {
  final image = await _render(px, shape: shape, glyph: glyph);
  final data = await image.toByteData(format: ui.ImageByteFormat.png);
  return data!.buffer.asUint8List();
}

Future<void> _write(String path, List<int> bytes) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsBytes(bytes);
  stdout.writeln('wrote $path (${bytes.length} bytes)');
}

Future<void> _writeText(String path, String text) {
  for (final comment in RegExp(r'<!--(.*?)-->', dotAll: true).allMatches(text)) {
    if (comment.group(1)!.contains('--')) {
      throw StateError('$path: a "--" inside an XML comment is not well-formed');
    }
  }
  return _write(path, utf8.encode(text));
}

// --- Android -------------------------------------------------------------

// XML comments may not contain a double hyphen (aapt2: "not well-formed"),
// so no `--` dashes in any comment text below.
const String _generated =
    '<!-- GENERATED by tool/generate_icons.dart from '
    'lib/widgets/ironpeak_logo.dart. Edit the Dart, then re-run '
    '`flutter test tool/generate_icons.dart`. -->';

Future<void> _writeAndroid() async {
  // Legacy launchers (API < 26 never ships: minSdk is 26) -- but nothing in
  // the app should still show the Flutter placeholder.
  const sizes = {
    'mdpi': 48,
    'hdpi': 72,
    'xhdpi': 96,
    'xxhdpi': 144,
    'xxxhdpi': 192,
  };
  for (final e in sizes.entries) {
    await _write('$_res/mipmap-${e.key}/ic_launcher.png', await _png(e.value));
  }

  await _writeText('$_res/mipmap-anydpi-v26/ic_launcher.xml', '''<?xml version="1.0" encoding="utf-8"?>
$_generated
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <!-- Android 13+ "themed icons": tinted with the wallpaper colors. -->
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
''');

  await _writeText('$_res/drawable/ic_launcher_background.xml', '''<?xml version="1.0" encoding="utf-8"?>
$_generated
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
${_gradientFill(indent: 8)}
    </path>
</vector>
''');

  await _writeText('$_res/drawable/ic_launcher_foreground.xml', _glyphVector(mono: false));
  await _writeText('$_res/drawable/ic_launcher_monochrome.xml', _glyphVector(mono: true));
  await _writeText('$_res/drawable/ic_splash_animated.xml', _splashAnimatedVector());
}

String _hex(Color c) =>
    '#${c.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase()}';

String _a(double v) {
  var s = v.toStringAsFixed(3);
  s = s.replaceFirst(RegExp(r'0+$'), '').replaceFirst(RegExp(r'\.$'), '');
  return s;
}

String _gradientFill({required int indent}) {
  final p = ' ' * indent;
  return '''$p<aapt:attr name="android:fillColor">
$p    <gradient
$p        android:type="linear"
$p        android:startX="0"
$p        android:startY="0"
$p        android:endX="108"
$p        android:endY="108">
$p        <item android:offset="0" android:color="${_hex(IronpeakMark.gradientStart)}" />
$p        <item android:offset="${_a(IronpeakMark.gradientMidStop)}" android:color="${_hex(IronpeakMark.gradientMid)}" />
$p        <item android:offset="1" android:color="${_hex(IronpeakMark.gradientEnd)}" />
$p    </gradient>
$p</aapt:attr>''';
}

String _pathTag(
  String data, {
  required Color color,
  double alpha = 1,
  String? name,
  int indent = 8,
}) {
  final p = ' ' * indent;
  return '$p<path\n'
      '${name == null ? '' : '$p    android:name="$name"\n'}'
      '$p    android:fillColor="${_hex(color)}"\n'
      '${alpha == 1 ? '' : '$p    android:fillAlpha="${_a(alpha)}"\n'}'
      '$p    android:pathData="$data" />';
}

// 108dp canvas, glyph box = the 66dp safe zone: unit -> x0.66, +21.
const String _glyphGroupOpen = '''    <group
        android:scaleX="0.66"
        android:scaleY="0.66"
        android:translateX="21"
        android:translateY="21">''';

String _glyphVector({required bool mono}) {
  const black = Color(0xFF000000);
  final backAlpha = mono ? IronpeakMark.monoBackPeakAlpha : IronpeakMark.backPeakAlpha;
  final frontAlpha = mono ? IronpeakMark.monoFrontPeakAlpha : IronpeakMark.frontPeakAlpha;
  final rock = mono ? black : IronpeakMark.rock;
  final snow = mono ? black : IronpeakMark.snow;
  final iron = mono ? black : IronpeakMark.iron;
  return '''<?xml version="1.0" encoding="utf-8"?>
$_generated
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
$_glyphGroupOpen
${_pathTag(IronpeakMark.backPeak, color: rock, alpha: backAlpha)}
${_pathTag(IronpeakMark.frontPeak, color: rock, alpha: frontAlpha)}
${_pathTag(IronpeakMark.backSnow, color: snow, alpha: 0.9)}
${_pathTag(IronpeakMark.frontSnow, color: snow)}
${mono ? '' : '${_pathTag(IronpeakMark.barbellShadow, color: black, alpha: IronpeakMark.shadowAlpha)}\n'}${_pathTag(IronpeakMark.barbell, color: iron)}
    </group>
</vector>
''';
}

int _ms(double seconds) => (seconds * 1000).round();

String _animator(
  String property,
  num from,
  num to, {
  required int duration,
  int offset = 0,
  String interpolator = '@android:interpolator/fast_out_slow_in',
}) {
  return '''    <target android:name="@@">
        <aapt:attr name="android:animation">
            <objectAnimator
                android:propertyName="$property"
                android:valueFrom="$from"
                android:valueTo="$to"
                android:valueType="floatType"
                android:duration="$duration"
${offset == 0 ? '' : '                android:startOffset="$offset"\n'}                android:interpolator="$interpolator" />
        </aapt:attr>
    </target>''';
}

/// The Android 12+ launch icon: same shapes as the launcher icon, but every
/// moving part starts in its t=0 pose (hidden / displaced) and is animated to
/// rest -- so a delayed animator never flashes the finished logo first. The
/// script mirrors IronpeakMark.poseAt's intro, number for number.
String _splashAnimatedVector() {
  final impact = _ms(IronpeakMark.impactSeconds);
  final targets = <String, List<String>>{
    'mountain': [
      _animator('scaleX', 0.86, 1, duration: 240),
      _animator('scaleY', 0.86, 1, duration: 240),
      _animator('scaleY', 1, 0.955,
          duration: 70,
          offset: impact,
          interpolator: '@android:anim/decelerate_interpolator'),
      _animator('scaleY', 0.955, 1,
          duration: 120,
          offset: impact + 70,
          interpolator: '@android:anim/decelerate_interpolator'),
    ],
    'backPeak': [_animator('fillAlpha', 0, IronpeakMark.backPeakAlpha, duration: 180)],
    'frontPeak': [_animator('fillAlpha', 0, IronpeakMark.frontPeakAlpha, duration: 180)],
    'backSnow': [_animator('fillAlpha', 0, 0.9, duration: 180)],
    'frontSnow': [_animator('fillAlpha', 0, 1, duration: 180)],
    'barbell': [
      _animator('translateY', -44, 0,
          duration: 520,
          offset: 80,
          interpolator: '@android:anim/bounce_interpolator'),
    ],
    'barbellShadow': [
      _animator('fillAlpha', 0, IronpeakMark.shadowAlpha,
          duration: 80, offset: 80, interpolator: '@android:anim/linear_interpolator'),
    ],
    'barbellIron': [
      _animator('fillAlpha', 0, 1,
          duration: 80, offset: 80, interpolator: '@android:anim/linear_interpolator'),
    ],
    'spark': [
      _animator('scaleX', 0, 1.15,
          duration: 140, offset: 260, interpolator: '@android:anim/decelerate_interpolator'),
      _animator('scaleY', 0, 1.15,
          duration: 140, offset: 260, interpolator: '@android:anim/decelerate_interpolator'),
      _animator('scaleX', 1.15, 0,
          duration: 240, offset: 400, interpolator: '@android:anim/accelerate_interpolator'),
      _animator('scaleY', 1.15, 0,
          duration: 240, offset: 400, interpolator: '@android:anim/accelerate_interpolator'),
      _animator('rotation', 0, 90,
          duration: 380, offset: 260, interpolator: '@android:anim/linear_interpolator'),
    ],
  };

  final targetXml = StringBuffer();
  targets.forEach((name, animators) {
    for (final a in animators) {
      targetXml.writeln(a.replaceFirst('@@', name));
    }
  });

  const disc = 'M18,54A36,36 0 1 1 90,54A36,36 0 1 1 18,54Z';
  return '''<?xml version="1.0" encoding="utf-8"?>
$_generated
<!-- Played once by the Android 12+ system splash screen
     (windowSplashScreenAnimatedIcon, see values-v31/styles.xml): the mountain
     pops in, the barbell drops onto it and bounces, a glint flashes. The disc
     is the 192dp circle the splash screen masks its icon to (2/3 of the
     108-unit canvas). Total length stays under the 1000ms limit. -->
<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
    <aapt:attr name="android:drawable">
        <vector
            android:width="108dp"
            android:height="108dp"
            android:viewportWidth="108"
            android:viewportHeight="108">
            <path android:pathData="$disc">
${_gradientFill(indent: 16)}
            </path>
            <group
                android:scaleX="0.66"
                android:scaleY="0.66"
                android:translateX="21"
                android:translateY="21">
                <group
                    android:name="mountain"
                    android:pivotX="${IronpeakMark.mountainPivot.dx.toInt()}"
                    android:pivotY="${IronpeakMark.mountainPivot.dy.toInt()}"
                    android:scaleX="0.86"
                    android:scaleY="0.86">
${_pathTag(IronpeakMark.backPeak, color: IronpeakMark.rock, alpha: 0, name: 'backPeak', indent: 20)}
${_pathTag(IronpeakMark.frontPeak, color: IronpeakMark.rock, alpha: 0, name: 'frontPeak', indent: 20)}
${_pathTag(IronpeakMark.backSnow, color: IronpeakMark.snow, alpha: 0, name: 'backSnow', indent: 20)}
${_pathTag(IronpeakMark.frontSnow, color: IronpeakMark.snow, alpha: 0, name: 'frontSnow', indent: 20)}
                </group>
                <group
                    android:name="barbell"
                    android:translateY="-44">
${_pathTag(IronpeakMark.barbellShadow, color: const Color(0xFF000000), alpha: 0, name: 'barbellShadow', indent: 20)}
${_pathTag(IronpeakMark.barbell, color: IronpeakMark.iron, alpha: 0, name: 'barbellIron', indent: 20)}
                </group>
                <group
                    android:name="spark"
                    android:translateX="${IronpeakMark.sparkAnchor.dx.toInt()}"
                    android:translateY="${IronpeakMark.sparkAnchor.dy.toInt()}"
                    android:scaleX="0"
                    android:scaleY="0">
${_pathTag(IronpeakMark.spark, color: IronpeakMark.snow, indent: 20)}
                </group>
            </group>
        </vector>
    </aapt:attr>
${targetXml.toString().trimRight()}
</animated-vector>
''';
}

// --- web -------------------------------------------------------------------

Future<void> _writeWeb() async {
  await _write('web/favicon.png', await _png(32));
  // Full-bleed squares: the platform masks them (iOS touch icon, maskable
  // PWA icons), and the glyph stays inside the maskable safe zone (80%).
  for (final px in [192, 512]) {
    final bytes = await _png(px, shape: LogoShape.square);
    await _write('web/icons/Icon-$px.png', bytes);
    await _write('web/icons/Icon-maskable-$px.png', bytes);
  }
}

// --- Windows .ico -----------------------------------------------------------

Future<void> _writeWindows() async {
  // Classic layout: DIB entries for the small sizes (what every shell
  // version understands), PNG for 256.
  const dibSizes = [16, 24, 32, 48, 64];
  final entries = <_IcoEntry>[];
  for (final px in dibSizes) {
    final image = await _render(px);
    final rgba = (await image.toByteData(format: ui.ImageByteFormat.rawStraightRgba))!
        .buffer
        .asUint8List();
    entries.add(_IcoEntry(px, _dib(px, rgba)));
  }
  entries.add(_IcoEntry(256, await _png(256)));
  await _write('windows/runner/resources/app_icon.ico', _ico(entries));
}

class _IcoEntry {
  _IcoEntry(this.size, this.data);
  final int size;
  final Uint8List data;
}

/// BITMAPINFOHEADER + bottom-up BGRA pixels + a (blank) 1-bit AND mask --
/// the alpha channel carries the transparency.
Uint8List _dib(int px, Uint8List rgba) {
  final maskRow = ((px + 31) ~/ 32) * 4;
  final maskBytes = maskRow * px;
  final out = BytesBuilder();
  final header = ByteData(40)
    ..setUint32(0, 40, Endian.little)
    ..setInt32(4, px, Endian.little)
    ..setInt32(8, px * 2, Endian.little) // XOR + AND mask heights
    ..setUint16(12, 1, Endian.little)
    ..setUint16(14, 32, Endian.little)
    ..setUint32(20, px * px * 4 + maskBytes, Endian.little);
  out.add(header.buffer.asUint8List());
  for (var y = px - 1; y >= 0; y--) {
    for (var x = 0; x < px; x++) {
      final i = (y * px + x) * 4;
      out.add([rgba[i + 2], rgba[i + 1], rgba[i], rgba[i + 3]]);
    }
  }
  out.add(Uint8List(maskBytes));
  return out.toBytes();
}

Uint8List _ico(List<_IcoEntry> entries) {
  final out = BytesBuilder();
  final dir = ByteData(6 + 16 * entries.length)
    ..setUint16(2, 1, Endian.little) // type: icon
    ..setUint16(4, entries.length, Endian.little);
  var offset = dir.lengthInBytes;
  for (var i = 0; i < entries.length; i++) {
    final e = entries[i];
    final o = 6 + 16 * i;
    dir
      ..setUint8(o, e.size >= 256 ? 0 : e.size)
      ..setUint8(o + 1, e.size >= 256 ? 0 : e.size)
      ..setUint16(o + 4, 1, Endian.little)
      ..setUint16(o + 6, 32, Endian.little)
      ..setUint32(o + 8, e.data.length, Endian.little)
      ..setUint32(o + 12, offset, Endian.little);
    offset += e.data.length;
  }
  out.add(dir.buffer.asUint8List());
  for (final e in entries) {
    out.add(e.data);
  }
  return out.toBytes();
}

// --- preview sheet -------------------------------------------------------------

/// A contact sheet to eyeball the design and the motion without a device:
/// the intro frames, the loop frames, and the adaptive icon under the common
/// launcher masks.
Future<void> _writePreview(Directory dir) async {
  await dir.create(recursive: true);
  const cell = 220.0;
  const pad = 14.0;
  final intro = [0.0, 0.06, 0.12, 0.20, 0.25, 0.30, 0.36, 0.44, 0.52, 0.64];
  final loop = [0.0, 0.7, 1.0, 1.25, 1.4, 1.7, 2.0, 2.3, 2.45, 2.8]
      .map((u) => IronpeakMark.introSeconds + u)
      .toList();

  const cols = 5;
  const rows = 5;
  const w = cols * (cell + pad) + pad;
  const h = rows * (cell + pad) + pad;

  Future<void> sheet(String name, Color bg) async {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    canvas.drawRect(const Rect.fromLTWH(0, 0, w, h), Paint()..color = bg);

    void draw(int row, int col, void Function(Canvas) body) {
      canvas.save();
      canvas.translate(pad + col * (cell + pad), pad + row * (cell + pad));
      body(canvas);
      canvas.restore();
    }

    for (var i = 0; i < intro.length; i++) {
      draw(i ~/ cols, i % cols, (c) {
        IronpeakMark.paint(c, const Size.square(cell),
            pose: IronpeakMark.poseAt(intro[i]));
      });
    }
    for (var i = 0; i < loop.length; i++) {
      draw(2 + i ~/ cols, i % cols, (c) {
        IronpeakMark.paint(c, const Size.square(cell),
            pose: IronpeakMark.poseAt(loop[i]));
      });
    }

    // Adaptive icon under launcher masks (circle, squircle-ish, rounded,
    // teardrop-ish) + the splash disc + a small-size legibility strip.
    final masks = <Path Function(double)>[
      (s) => Path()..addOval(Rect.fromLTWH(s * 0.5 - s * 0.333, s * 0.5 - s * 0.333, s * 0.667, s * 0.667)),
      (s) => Path()
        ..addRRect(RRect.fromRectAndRadius(
            Rect.fromCenter(center: Offset(s / 2, s / 2), width: s * 0.667, height: s * 0.667),
            Radius.circular(s * 0.667 * 0.32))),
      (s) => Path()
        ..addRRect(RRect.fromRectAndRadius(
            Rect.fromCenter(center: Offset(s / 2, s / 2), width: s * 0.667, height: s * 0.667),
            Radius.circular(s * 0.667 * 0.16))),
      (s) => Path()
        ..addRRect(RRect.fromRectAndCorners(
            Rect.fromCenter(center: Offset(s / 2, s / 2), width: s * 0.667, height: s * 0.667),
            topLeft: Radius.circular(s * 0.667 * 0.5),
            topRight: Radius.circular(s * 0.667 * 0.5),
            bottomLeft: Radius.circular(s * 0.667 * 0.5),
            bottomRight: Radius.circular(s * 0.667 * 0.1))),
    ];
    for (var i = 0; i < masks.length; i++) {
      draw(4, i, (c) {
        c.clipPath(masks[i](cell));
        IronpeakMark.paint(c, const Size.square(cell),
            shape: LogoShape.square,
            glyphFraction: IronpeakMark.launcherGlyphFraction);
      });
    }
    // Real-size legibility: 48 / 72 / 96 dp equivalents, side by side.
    draw(4, 4, (c) {
      var x = 0.0;
      for (final px in [48.0, 72.0, 96.0]) {
        c.save();
        c.translate(x, cell / 2 - px / 2);
        c.clipRRect(RRect.fromRectAndRadius(
            Offset.zero & Size.square(px), Radius.circular(px * 0.5)));
        IronpeakMark.paint(c, Size.square(px),
            shape: LogoShape.square,
            glyphFraction: IronpeakMark.launcherGlyphFraction);
        c.restore();
        x += px + 6;
      }
    });

    final image = await recorder.endRecording().toImage(w.toInt(), h.toInt());
    final data = await image.toByteData(format: ui.ImageByteFormat.png);
    await File('${dir.path}/$name').writeAsBytes(data!.buffer.asUint8List());
    stdout.writeln('preview: ${dir.path}/$name');
  }

  await sheet('preview_light.png', const Color(0xFFF1F1F4));
  await sheet('preview_dark.png', const Color(0xFF101114));
}
